server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Todo lo que empiece por /api 
    # lo redirige al backend en el puerto 3000
    # El frontend llama a /api/activity
    # nginx lo convierte en http://backend:3000/activity
    location /api/ {
        proxy_pass http://backend:3000/;
        
        # Cabeceras necesarias para que el backend
        # sepa la IP real del cliente
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Necesario para las cookies de sesión
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}